name: swimming_app_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  table_calendar: ^3.2.0
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.4
  flutter_svg: ^2.2.0
  intl_phone_field: ^3.2.0
  pinput: ^5.0.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  polar: ^7.7.0
  fl_chart: ^1.0.0
  animated_toggle_switch: ^0.8.5
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  syncfusion_flutter_gauges: ^30.1.41
  syncfusion_flutter_charts: ^30.2.6
  easy_date_timeline: ^2.0.9
  modal_bottom_sheet: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

# dependency_overrides:
#   dartx: ^0.3.0
#   quiver: ^2.1.3

flutter:
  uses-material-design: true
  assets:
      - assets/svg/
      - assets/svg/self_talk/
      - assets/svg/nerves/
      - assets/svg/energy_level/
      - assets/svg/breathing/
      - assets/svg/catch_feel/
      - assets/svg/stroke_length/
      - assets/svg/kick_technique/
      - assets/svg/kick_throughout/
      - assets/svg/head_position/
      - assets/svg/turn/
      

      - assets/images/..
